const colors = {
  light: {
    text: "#1a1a1a",
    tint: "#0e7c7b",
    background: "#f2f2f2",
    foreground: "#1a1a1a",
    card: "#ffffff",
    cardForeground: "#1a1a1a",
    primary: "#0e7c7b",
    primaryForeground: "#ffffff",
    secondary: "#e6f2f1",
    secondaryForeground: "#0e7c7b",
    muted: "#eef2f1",
    mutedForeground: "#6b7a78",
    accent: "#e6f2f1",
    accentForeground: "#0a5c5b",
    destructive: "#e03131",
    destructiveForeground: "#ffffff",
    success: "#0e7c7b",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    border: "#e2e8e7",
    input: "#e2e8e7",
    ring: "#0e7c7b",
  },
  radius: 10,
};

export default colors;
